
int bitAnd(int, int);
int test_bitAnd(int, int);
int getByte(int, int);
int test_getByte(int, int);
int logicalShift(int, int);
int test_logicalShift(int, int);
int rotateRight(int, int);
int test_rotateRight(int, int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int bang(int);
int test_bang(int);
int bitParity(int);
int test_bitParity(int);
int isTmax(int);
int test_isTmax(int);
int fitsBits(int, int);
int test_fitsBits(int, int);
int divpwr2(int, int);
int test_divpwr2(int, int);
int negate(int);
int test_negate(int);
int isPositive(int);
int test_isPositive(int);
int isGreater(int, int);
int test_isGreater(int, int);
int subOK(int, int);
int test_subOK(int, int);
int ilog2(int);
int test_ilog2(int);
